apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: imagepolicy-sample
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 5.0.x
